// Local data URLs retain the same typefaces under HTTP and direct file:// launch.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const faces = [
  ['Barlow', 'barlow', [400,500,600,700,800]],
  ['Barlow Condensed', 'barlowcondensed', [600,700,800]],
];
const rules = faces.flatMap(([family, name, weights]) => weights.map(weight => {
  const bytes = fs.readFileSync(path.join(root, `assets/fonts/${name}-${weight}.ttf`));
  return `@font-face { font-family: '${family}'; font-weight: ${weight}; font-display: swap; src: url('data:font/ttf;base64,${bytes.toString('base64')}') format('truetype'); }`;
}));
fs.writeFileSync(path.join(root, 'assets/fonts/fonts.css'), '/* Generated by tools/build_fonts.cjs from OFL-licensed local font files. */\n' + rules.join('\n') + '\n');
console.log('Built local font stylesheet (8 faces).');
