// Keep the browser textures identical to Blender's PNGs while supporting file://.
// Image requests for neighboring files are not valid WebGL texture sources in Chrome.
const fs = require('node:fs');
const path = require('node:path');
const directory = path.resolve(__dirname, '../assets/track');
const textures = {};
for (const name of ['speedway-asphalt', 'speedway-wall', 'speedway-mesh']) {
  textures[name] = 'data:image/png;base64,' + fs.readFileSync(path.join(directory, `${name}.png`)).toString('base64');
}
fs.writeFileSync(path.join(directory, 'track-textures.js'),
  '// Generated by tools/pack_track_textures.cjs from the original track PNGs.\n' +
  'const SC_TRACK_TEXTURES = ' + JSON.stringify(textures) + ';\n');
console.log('Packed three track textures for direct-file and hosted play.');
